// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class CarTypeThuannt
{
    public int CarTypeThuanntId { get; set; }

    public string Name { get; set; }

    public string Manufacture { get; set; }

    public string Category { get; set; }

    public double? BasePrice { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CarThuannt> CarThuannts { get; set; } = new List<CarThuannt>();
}