// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class CarThuannt
{
    public int CarThuanntId { get; set; }

    public string CarName { get; set; }

    public double? MaxEnergy { get; set; }

    public DateTime? MaintenanceDate { get; set; }

    public DateTime? NextMaintenanceDate { get; set; }

    public int? CarTypeId { get; set; }

    public string Color { get; set; }

    public string LicensePlate { get; set; }

    public string Manufacture { get; set; }

    public double? CurrentKm { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual CarTypeThuannt CarType { get; set; }

    public virtual ICollection<MaintainingDuynt> MaintainingDuynts { get; set; } = new List<MaintainingDuynt>();
}