// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class CenterPartThanNth
{
    [Key]
    public int CenterPartThanNthid { get; set; }

    public int? PartId { get; set; }

    public int CenterId { get; set; }

    public int? AvailableQuantity { get; set; }

    public int? MinimumQuantity { get; set; }

    public string Description { get; set; }

    public string PartStatus { get; set; }

    public bool? IsDeleted { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ServiceCenterHieupt Center { get; set; }

    public virtual PartThanNth Part { get; set; }
}