// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class CenterRevenueHieuPt
{
    public int CenterRevenueHieuPtid { get; set; }

    public int? ServiceCenterId { get; set; }

    public string RevenueTitle { get; set; }

    public double? Expense { get; set; }

    public double? Revenue { get; set; }

    public double? NetProfit { get; set; }

    public string Note { get; set; }

    public string ReportPeriod { get; set; }

    public DateTime? CreateDate { get; set; }

    public int? ReportBy { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual SystemUserAccount ReportByNavigation { get; set; }

    public virtual ServiceCenterHieupt ServiceCenter { get; set; }
}