// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class Certificate
{
    public int CertificateId { get; set; }

    public int UserId { get; set; }

    public string Specialized { get; set; }

    public string SchoolName { get; set; }

    public string Achievement { get; set; }

    public bool? Graduation { get; set; }

    public virtual SystemUserAccount User { get; set; }
}