// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class MaintaningTypeDuynt
{
    public int MaintainingTypeDuyntId { get; set; }

    public string MaintaningTypeName { get; set; }

    public DateTime? CreateDate { get; set; }

    public bool? IsInstalled { get; set; }

    public virtual ICollection<MaintainingDuynt> MaintainingDuynts { get; set; } = new List<MaintainingDuynt>();
}