// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class MaintainingDuynt
{
    public int MaintainingDuyntId { get; set; }

    public int? CarId { get; set; }

    public int? OrderId { get; set; }

    public int? ServiceId { get; set; }

    public int? MaintainingTypeId { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? TechnicianId { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual CarThuannt Car { get; set; }

    public virtual MaintaningTypeDuynt MaintainingType { get; set; }

    public virtual OrderLamtv Order { get; set; }

    public virtual ServiceThongnm Service { get; set; }

    public virtual SystemUserAccount Technician { get; set; }
}