// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class OrderLamtv
{
    public int OrderLamtvId { get; set; }

    public int UserId { get; set; }

    public int OrderTypeId { get; set; }

    public double? TotalPrice { get; set; }

    public string Description { get; set; }

    public string OrderStatus { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string PaymentMethod { get; set; }

    public int ServiceCenterId { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<MaintainingDuynt> MaintainingDuynts { get; set; } = new List<MaintainingDuynt>();

    public virtual OrderTypeLamtv OrderType { get; set; }

    public virtual ServiceCenterHieupt ServiceCenter { get; set; }

    public virtual SystemUserAccount User { get; set; }
}