// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class OrderTypeLamtv
{
    public int OrderTypeLamtvId { get; set; }

    public string OrderTypeName { get; set; }

    public string Status { get; set; }

    public virtual ICollection<OrderLamtv> OrderLamtvs { get; set; } = new List<OrderLamtv>();
}