// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class PartThanNth
{
    [Key]
    public int PartThanNthid { get; set; }

    public string PartName { get; set; }

    public double? Price { get; set; }

    public string CompanyName { get; set; }

    public string Description { get; set; }

    public virtual ICollection<CenterPartThanNth> CenterPartThanNths { get; set; } = new List<CenterPartThanNth>();
}
