// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class ServiceCenterHieupt
{
    public int ServiceCenterHieuptId { get; set; }

    public string ServiceCenterName { get; set; }

    public string Address { get; set; }

    public string Status { get; set; }

    public TimeOnly? TimeOpen { get; set; }

    public TimeOnly? TimeClose { get; set; }

    public double? Rating { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<CenterPartThanNth> CenterPartThanNths { get; set; } = new List<CenterPartThanNth>();

    public virtual ICollection<CenterRevenueHieuPt> CenterRevenueHieuPts { get; set; } = new List<CenterRevenueHieuPt>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<OrderLamtv> OrderLamtvs { get; set; } = new List<OrderLamtv>();

    public virtual ICollection<ServiceThongnm> ServiceThongnms { get; set; } = new List<ServiceThongnm>();

    public virtual ICollection<ShiftsNamPk> ShiftsNamPks { get; set; } = new List<ShiftsNamPk>();

    public virtual ICollection<ServiceThongnm> Services { get; set; } = new List<ServiceThongnm>();
}