// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class ServiceFeedback
{
    public int ServiceFeedbackId { get; set; }

    public int? ServiceId { get; set; }

    public int? UserId { get; set; }

    public string Description { get; set; }

    public DateTime? FeedbackDate { get; set; }

    public virtual ServiceThongnm Service { get; set; }

    public virtual SystemUserAccount User { get; set; }
}