// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class ServiceThongnm
{
    public int ServiceThongnmId { get; set; }

    public int? ServiceTypeId { get; set; }

    public string ServiceName { get; set; }

    public double? TotalPrice { get; set; }

    public DateTime? TimeMaintenance { get; set; }

    public DateTime? DurationTime { get; set; }

    public string Category { get; set; }

    public int? ServiceCenterId { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public string Status { get; set; }

    public bool? IsDeleted { get; set; }

    public virtual ICollection<MaintainingDuynt> MaintainingDuynts { get; set; } = new List<MaintainingDuynt>();

    public virtual ServiceCenterHieupt ServiceCenter { get; set; }

    public virtual ICollection<ServiceFeedback> ServiceFeedbacks { get; set; } = new List<ServiceFeedback>();

    public virtual ServiceTypeThongnm ServiceType { get; set; }

    public virtual ICollection<ServiceCenterHieupt> ServiceCenters { get; set; } = new List<ServiceCenterHieupt>();
}