// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class ServiceTypeThongnm
{
    public int ServiceTypeThongnmId { get; set; }

    public string Description { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? Premium { get; set; }

    public bool? IsInstalled { get; set; }

    public virtual ICollection<ServiceThongnm> ServiceThongnms { get; set; } = new List<ServiceThongnm>();
}