// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class ShiftsNamPk
{
    public int ShiftNamPkId { get; set; }

    public DateTime? TimeStart { get; set; }

    public DateTime? TimeEnd { get; set; }

    public string WorkingNote { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public int? ManagerId { get; set; }

    public bool? ShiftStatus { get; set; }

    public int ServiceCenterId { get; set; }

    public double? TotalTimeWorkingOnDay { get; set; }

    public virtual SystemUserAccount Manager { get; set; }

    public virtual ServiceCenterHieupt ServiceCenter { get; set; }

    public virtual ICollection<UserShiftsNamPk> UserShiftsNamPks { get; set; } = new List<UserShiftsNamPk>();
}