// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class SystemUserAccount
{
    public int UserAccountId { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string EmployeeCode { get; set; }

    public int RoleId { get; set; }

    public string RequestCode { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string ApplicationCode { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public string ModifiedBy { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CenterRevenueHieuPt> CenterRevenueHieuPts { get; set; } = new List<CenterRevenueHieuPt>();

    public virtual ICollection<Certificate> Certificates { get; set; } = new List<Certificate>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<MaintainingDuynt> MaintainingDuynts { get; set; } = new List<MaintainingDuynt>();

    public virtual ICollection<OrderLamtv> OrderLamtvs { get; set; } = new List<OrderLamtv>();

    public virtual ICollection<ServiceFeedback> ServiceFeedbacks { get; set; } = new List<ServiceFeedback>();

    public virtual ICollection<ShiftsNamPk> ShiftsNamPks { get; set; } = new List<ShiftsNamPk>();

    public virtual ICollection<UserShiftsNamPk> UserShiftsNamPks { get; set; } = new List<UserShiftsNamPk>();
}