// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class UsePart
{
    public int? CenterPartId { get; set; }

    public int? MaintainingId { get; set; }

    public int? PartId { get; set; }

    public int? Quantity { get; set; }

    public bool? Status { get; set; }

    public DateTime? CreateDate { get; set; }

    public virtual CenterPartThanNth CenterPart { get; set; }

    public virtual MaintainingDuynt Maintaining { get; set; }
}