// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EVServiceCenter.Repositories.ThanNTH.Models;

public partial class UserShiftsNamPk
{
    public int UserShiftsNamPkId { get; set; }

    public int ShiftId { get; set; }

    public int UserId { get; set; }

    public string WorkingStatus { get; set; }

    public int? Rating { get; set; }

    public virtual ShiftsNamPk Shift { get; set; }

    public virtual SystemUserAccount User { get; set; }
}